# Generated by Django 4.0.2 on 2022-02-22 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('user_type', models.CharField(choices=[('s_admin', 'sales_admin'), ('s_representative', 'sales_representative'), ('none', 'None')], default='None', max_length=100)),
                ('user_bio', models.CharField(blank=True, max_length=300, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
