# Generated by Django 4.0.2 on 2022-02-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_lead_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager_id',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
