# Generated by Django 4.0.2 on 2022-02-22 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_remove_user_manager_id_delete_lead_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('user_type', models.CharField(choices=[('s_admin', 'sales_admin'), ('s_representative', 'sales_representative'), ('none', 'None')], default='None', max_length=100)),
                ('user_bio', models.CharField(blank=True, max_length=300, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authentication.user')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('state', models.CharField(choices=[('hot', 'hot'), ('cold', 'cold'), ('med', 'med'), ('sold', 'sold'), ('na', 'na')], default='na', max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
