# Generated by Django 4.0.2 on 2022-02-24 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lead')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user')),
            ],
        ),
    ]
